import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: "doc",
      label: "Intro",
      id: "intro",
    },
    {
      type: "doc",
      label: "Resources",
      id: "resources",
    },
    {
      type: "doc",
      label: "TODO",
      id: "todo",
    },
    {
      type: "category",
      label: "Questions",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "HTML",
          id: "questions/html",
        },
        {
          type: "doc",
          label: "CSS",
          id: "questions/css",
        },
        {
          type: "doc",
          label: "Javascript",
          id: "questions/javascript",
        },
        {
          type: "doc",
          label: "Typecript",
          id: "questions/typescript",
        },
        {
          type: "doc",
          label: "React",
          id: "questions/react",
        },
        {
          type: "doc",
          label: "Testing",
          id: "questions/testing",
        },
        {
          type: "doc",
          label: "Fundamentals",
          id: "questions/fundamentals",
        },
        {
          type: "doc",
          label: "A11Y",
          id: "questions/a11y",
        },
      ],
    },
    {
      type: "category",
      label: "Answers",
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "HTML",
          id: "answers/html",
        },
        {
          type: "doc",
          label: "CSS",
          id: "answers/css",
        },
        {
          type: "doc",
          label: "Javascript",
          id: "answers/javascript",
        },
        {
          type: "doc",
          label: "Typecript",
          id: "answers/typescript",
        },
        {
          type: "doc",
          label: "React",
          id: "answers/react",
        },
        {
          type: "doc",
          label: "Testing",
          id: "answers/testing",
        },
        {
          type: "doc",
          label: "Fundamentals",
          id: "answers/fundamentals",
        },
        {
          type: "doc",
          label: "A11Y",
          id: "answers/a11y",
        },
      ],
    },
  ],
};

export default sidebars;
